benchmarks:
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 30000, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 256}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"