benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 32, end: 268435456, multiplier: 2}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 16}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs-nccl"
