benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 256, end: 30000, multiplier: 2}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 256}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
  trace_dir: "/tmp/microbenchmarks/trace-all-gather"
