apiVersion: v1
kind: Pod
metadata:
  name: tpu7x-single-host-microbenchmark
spec:
  restartPolicy: Never
  nodeSelector:
    cloud.google.com/gke-tpu-accelerator: tpu7x
    cloud.google.com/gke-tpu-topology: 2x2x1
  containers:
  - name: tpu-job
    image: vllm/vllm-tpu:ironwood
    ports:
    - containerPort: 8431
    securityContext:
      privileged: false
    command:
    - bash
    - -c
    - |
      set -ex
      git clone https://github.com/vllm-project/tpu-inference.git
      cd tpu-inference
      git checkout jacobplatin/janus-benchmarking-ext
      pip install tensorflow
      python benchmarking/benchmark_janus.py
    resources:
      requests:
        google.com/tpu: 4
      limits:
        google.com/tpu: 4